name: 42Crunch API Security Audit

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run_42c_audit:
    permissions:
      contents: read
      security-events: write
    name: 42Crunch API Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: 42crunch-static-api-testing
        uses: 42crunch/api-security-audit-action-freemium@main
        with:
          upload-to-code-scanning: true
          enforce-sqg: false
          sarif-report: 42Crunch_AuditReport_${{ github.run_id }}.SARIF
          log-level: debug

      - name: Upload SARIF file to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 42Crunch_AuditReport_${{ github.run_id }}.SARIF
          path: 42Crunch_AuditReport_${{ github.run_id }}.SARIF
